### ISSUE TITLE
Images referenced with (absolute) pathes in .md files are not displayed

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/markdown-joiner#23]

**Comment by msevestre** [comment]
Yes this does not work. The PDF processor files needs to download all files locally and create local absolute files in order to be able to create PDF.

@Yuri05 
I am not quite sure how this can work to be honest aside from parsing the markdown file for references and try downloading them

Or  we define some "ContentImages" section in the Section with the list of images to include. This is easier for us but much harder to get right for the user

**Comment by sfrechen** [comment]
> Or we define some "ContentImages" section in the Section with the list of images to include. This is easier for us but much harder to get right for the user

Dislike :)

**Comment by msevestre** [comment]
@sfrechen Yeah I agree. This is not a good idea :) I don't like it eiter

**Comment by msevestre** [comment]
see #32 PDF will now be creaeted using typora. If typora supports this, it will work
