### ISSUE TITLE
'Hard-coded' folder-link in md-files

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/markdown-joiner#31]
It would be great if the figures links in the MD files do not refer to the actual folder location, but rather an eg.  .\  (subfolder) location. otherwise when copying output to another pc, the figure links are not working anymore obviously :).

e.g. currently: 

Simulated versus observed plasma concentration-time profiles of all data are shown below.
![001_plotTimeProfile.png](C:\Users\x.x\Desktop\Markdown\x\report-output\markdown_for_pdf\003_3_Results_and_Discussion\Concentration-Time_profiles\001_plotTimeProfile.png)

**Comment by msevestre** [comment]
This is already the case with the markdown folder that uses relative paths. The markdown-for-pdf folder is, as the name somewhat implies, only used for the PDF generation that requires absolute paths. Do not use this folder for anything else!

**Comment by Incei** [comment]
is there any other difference between the mardown vs markdown-for-pdf folder? 
please dont close topic without feedback. :)

**Comment by Incei** [comment]
The matlabscript we are currently using applies markdown-for-pdf folder to create the merged MD file. We use Typora currently to load this md file and generate a PDF out of it. 

Currently the MD folders do not create the correct relative path. It is storing only the filenames of the figure files because the figures are stored under the same folder, which is not the case for the merged MD file. 

I then suggest that we keep everything as it is for now, and always create a PDF directly from where the MD files are created (using the markdown-for-pdf folder!). Otherwise it doesnt work and one needs to update the paths in the merged-file).

**Comment by msevestre** [comment]
In the issue description, you were explaining that you wanted to copy the markdown to another computer. For this purpose the markdown-for-pdf folder is not appropriate.

If the goal is to however to create a PDF, then the markdown-for-pdf is potentially what you could use. I do not see any problem with that. 

However, if you want to upload the markdown to GitHub (which should be done in my opinion as it is much easier to read than a PDF) you should use the markdown folder. I hope I could clarify.


In terms of not closing issues before I receive feedback...that would be a dream for me. However we almost never get feedback, even if we ask. That's why we need to close issues when we believe they are solved.

**Comment by msevestre** [comment]
I have reopened the issue. Please close when appropriate

**Comment by Incei** [comment]
@msevestre many thanks for the clarification. Ok, so for github we should upload the Markdown folder content including the subfolders, and only for pdf-creation the markdown-for-pdf.  That is perfectly fine :). 

I would then upload always the final pdf, the markdown-folder and optionally the html-folder when we have a final package. Or would you suggest to also upload the markdown-for-pdf folder? To have a clean repository i would not upload that (due to the absolute-path-links).

**Comment by msevestre** [comment]
obsolete
